version: '3.8'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_CONNECTION_STRING: mongodb://test:password@mongodb:27017/testdb
    networks:
      - test-network
    depends_on:
      - database
    command: npm run dev

  database:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: testdb
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - database-data:/data/db
    networks:
      - test-network

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - test-network
    depends_on:
      - database

networks:
  test-network:
    driver: bridge

volumes:
  database-data: