 module.exports = {
                   "mhdr": {
                    "id": "fea732f6-8c5b-42e8-af0c-b3a63bbf7833",
                    "format": "CAD_LV_RSP",
                    "ver": "1.0.1",
                    "sessionId": "ba6835cf-0b70-4138-9b06-98cc9feeb797",
                    "lang": null,
                    "langcfg": null,
                    "routing": {
                     "orig": "geocoding-74db7bbb8c-hfzz5.19556",
                     "dest": "website-64bf9b7c7b-v6rp9.36924",
                     "reply": null,
                     "host": null,
                     "ttl": "2023-03-15T13:36:21.7030891+00:00",
                     "rte": 1,
                     "proc": 2,
                     "subtime": "0001-01-01T00:00:00+00:00"
                    },
                    "response": {
                     "success": true,
                     "msgs": []
                    },
                    "allowAsync": false,
                    "utcOffset": 0,
                    "enableAudit": null
                   },
                   "body": {
                    "results": [
                     {
                      "loc": "10 NEW SQUARE LONDON WC2A 3QG",
                      "conf": 1,
                      "match": "verified",
                      "addrtyp": 0,
                      "lat": 51.5155921,
                      "lon": -0.1142471,
                      "drlat": 0,
                      "drlon": 0,
                      "num": null,
                      "AddNumFrom": null,
                      "AddNumTo": null,
                      "dirpre": null,
                      "feanme": null,
                      "featyp": null,
                      "dirsuf": null,
                      "mun": null,
                      "area": null,
                      "apt": null,
                      "bldg": null,
                      "locfld1": null,
                      "locfld2": null,
                      "locfld3": null,
                      "locfld4": null,
                      "zip": null,
                      "xst1": "",
                      "xst2": "",
                      "cmt": "10",
                      "addrid": null,
                      "esz": 0,
                      "providerToken": null,
                      "fromAniAli": false,
                      "providerName": "GeocodingInterface",
                      "locationVerifiedTime": null,
                      "locationType": null,
                      "placeName": null,
                      "state": null,
                      "unitType": null,
                      "layerName": "",
                      "providerResponse": "[type, 24][id, 5210L000024220][uprn, 5086877][usrn, 20401252][logical_status, 1][language, ENG][classification_code, CR08][parent_uprn, ][country, E][authority, LONDON BOROUGH OF CAMDEN][longitude, -0.1142471][latitude, 51.5155921][easting, 530944][northing, 181315][full_building_desc, 10][formattedaddress, 10 NEW SQUARE\r\nLONDON\r\nWC2A 3QG][organisation, ][secondary_name, ][sao_text, ][sao_nums, ][primary_name, 10][pao_text, ][pao_nums, 10][street, NEW SQUARE][locality, ][town, LONDON][post_town, ][postcode, WC2A 3QG][crossref, ]"
                     },
                     {
                      "loc": "PAYNE HICKS BEACH 10 NEW SQUARE LONDON WC2A 3QG",
                      "conf": 1,
                      "match": "verified",
                      "addrtyp": 0,
                      "lat": 51.5155921,
                      "lon": -0.1142471,
                      "drlat": 0,
                      "drlon": 0,
                      "num": null,
                      "AddNumFrom": null,
                      "AddNumTo": null,
                      "dirpre": null,
                      "feanme": null,
                      "featyp": null,
                      "dirsuf": null,
                      "mun": null,
                      "area": null,
                      "apt": null,
                      "bldg": null,
                      "locfld1": null,
                      "locfld2": null,
                      "locfld3": null,
                      "locfld4": null,
                      "zip": null,
                      "xst1": "",
                      "xst2": "",
                      "cmt": "10",
                      "addrid": null,
                      "esz": 0,
                      "providerToken": null,
                      "fromAniAli": false,
                      "providerName": "GeocodingInterface",
                      "locationVerifiedTime": null,
                      "locationType": null,
                      "placeName": null,
                      "state": null,
                      "unitType": null,
                      "layerName": "",
                      "providerResponse": "[type, 28][id, 28_26253003_ENG][uprn, 5086877][usrn, 0][logical_status, 1][language, ENG][classification_code, CR08][parent_uprn, ][country, ][authority, ][longitude, -0.1142471][latitude, 51.5155921][easting, 530944][northing, 181315][full_building_desc, 10][formattedaddress, PAYNE HICKS BEACH\r\n10 NEW SQUARE\r\nLONDON\r\nWC2A 3QG][organisation, PAYNE HICKS BEACH][secondary_name, ][sao_text, ][sao_nums, ][primary_name, 10][pao_text, ][pao_nums, 10][street, NEW SQUARE][locality, ][town, ][post_town, LONDON][postcode, WC2A 3QG][crossref, ]"
                     }
                    ],
                    "suggest": false
                   }
                  };