 module.exports = {
       "mhdr": {
        "id": "df888895-a63f-4f3a-9649-561214751324",
        "format": "CREDIALOG_RSP",
        "ver": "1.0.0",
        "sessionId": "76699a00-3634-4863-b740-51d6f0cfdc38",
        "lang": null,
        "langcfg": null,
        "routing": {
         "orig": "creclient-6dd59c48f9-dzstv.18868",
         "dest": "website-67b974d565-wm92k.974856",
         "reply": null,
         "host": null,
         "ttl": "2023-01-06T14:45:33.5779129+00:00",
         "rte": 1,
         "proc": 2,
         "subtime": "0001-01-01T00:00:00+00:00"
        },
        "response": {
         "success": true,
         "msgs": [
          ""
         ]
        },
        "allowAsync": false,
        "utcOffset": 0,
        "enableAudit": null
       },
       "body": {
        "creStateData": {
         "ruleString": "ExternalWebSites",
         "args": [],
         "agencyEventId": [],
         "unitId": [],
         "responseIndicator": null,
         "responseString": "",
         "continueIndicator": true,
         "ruleIdString": "a29de89c-3d16-4e7a-b403-40ca945479cb",
         "createEventData": {
          "location": {
           "loc": "10 NEW SQUARE LONDON WC2A 3QG",
           "conf": 0,
           "match": null,
           "addrtyp": 0,
           "lat": 0,
           "lon": 0,
           "drlat": 0,
           "drlon": 0,
           "num": null,
           "AddNumFrom": null,
           "AddNumTo": null,
           "dirpre": null,
           "feanme": null,
           "featyp": null,
           "dirsuf": null,
           "mun": null,
           "area": null,
           "apt": null,
           "bldg": null,
           "locfld1": null,
           "locfld2": null,
           "locfld3": null,
           "locfld4": null,
           "zip": null,
           "xst1": null,
           "xst2": null,
           "cmt": null,
           "addrid": null,
           "esz": 0,
           "providerToken": null,
           "fromAniAli": false,
           "providerName": null,
           "locationVerifiedTime": null,
           "locationType": null,
           "placeName": null,
           "state": null,
           "unitType": null,
           "layerName": null,
           "providerResponse": null
          },
          "alarmlevel": 0,
          "tycod": "A01",
          "sub_tycod": "AQ01",
          "deplo": [
           {
            "ag": "MPS",
            "evnum": null,
            "alarmlev": 0,
            "evstat": 0,
            "evsubstat": 0,
            "sTime": null,
            "r": false,
            "dg": "",
            "lev2": "",
            "lev3": "",
            "lev4": "",
            "lev5": "",
            "esz": -1,
            "prio": 3,
            "eta": 0,
            "disporeq": false,
            "loiavail": 30,
            "t1": 0,
            "t2": 0,
            "t3": 0,
            "t4": 0,
            "majevt": null,
            "tycod": "A01",
            "tydesc": "Anti Social Behaviour (ASB) - Personal",
            "sub_tycod": "AQ01",
            "subtydesc": "Inconsiderate Behaviour - Illegal Encampments",
            "neardist": 0,
            "loidist": 0,
            "caseid": 0,
            "ascase": 0,
            "duration": 0
           }
          ],
          "call": {
           "id": null,
           "first": false,
           "source": null,
           "time": "0001-01-01T00:00:00+00:00",
           "name": null,
           "addr": null,
           "num": null,
           "commonEventCallId": null,
           "lat": 0,
           "lon": 0,
           "calltakerCallId": null,
           "additionalinfo": {
            "dob": null,
            "dl": null,
            "height": null,
            "middlename": null,
            "race": null,
            "sex": null,
            "weight": null,
            "city": null,
            "state": null,
            "streetaddr": null
           },
           "anialinumber": null,
           "custom_data": {},
           "createdTime": null,
           "updatedTime": null
          },
          "com": [],
          "suppl": [],
          "sched": {
           "pickup": null,
           "drop": null,
           "requested": null,
           "name": null,
           "unit": null,
           "droploc": null
          },
          "attachments": [],
          "evdesc": null,
          "proqacase": null,
          "casetype": null,
          "phonetype": null,
          "remoteEventId": null,
          "remoteAgencyId": null,
          "locationVerification": 0,
          "custom_data": {}
         },
         "updateEventData": null,
         "commands": [],
         "comments": [],
         "gadgetVariablesToGet": [],
         "gadgetVariablesToSet": [],
         "dialogTitleString": "ExternalWebSites",
         "dialogVersionString": "1.0.0",
         "overrideDialogTitleString": null,
         "hideBackButton": true,
         "hideCancelButton": true,
         "hideSubmitButton": true,
         "showExtraSubmitButton": false,
         "backButtonText": "COMMAND_DIALOG_BACK",
         "cancelButtonText": "COMMAND_DIALOG_CANCEL",
         "submitButtonText": "COMMAND_DIALOG_VIEW_WEBSITES",
         "extraSubmitButtonText": "",
         "clickedButtonText": null,
         "wavFiles": [],
         "urisToOpen": [],
         "customField1": [
          {
           "Column0Value": "Bus Locations",
           "Column1Value": "https://traintimes.org.uk/map/london-buses",
           "Column2Value": "Bus Locations"
          },
          {
           "Column0Value": "Defib Locations",
           "Column1Value": "http://www.heartsafe.org.uk/aed-locations",
           "Column2Value": "Defib Locations"
          },
          {
           "Column0Value": "Google",
           "Column1Value": "www.google.com",
           "Column2Value": "Google"
          },
          {
           "Column0Value": "IIP",
           "Column1Value": "https://iipcdw.aware.mps/iipsearch/search/SearchType.do",
           "Column2Value": "IIP"
          },
          {
           "Column0Value": "InfoPortal",
           "Column1Value": "https://apps.powerapps.com/play/27d90bd7-9248-4ab1-b9b5-46ceebf89718?tenantId=f3ee2a7e-7235-4d28-ab42-617c4c17f0c1",
           "Column2Value": "InfoPortal"
          },
          {
           "Column0Value": "PNC",
           "Column1Value": "http://zdc0002pnc/pncbrowser/start.asp",
           "Column2Value": "PNC"
          },
          {
           "Column0Value": "Postcode Finder",
           "Column1Value": "https://www.royalmail.com",
           "Column2Value": "Lookup the postcode for a location"
          },
          {
           "Column0Value": "WebStation",
           "Column1Value": "http://myplanner.foundation.met.police.uk/web/guest",
           "Column2Value": "WebStation"
          },
          {
           "Column0Value": "What3Words",
           "Column1Value": "https://what3words.com",
           "Column2Value": "External Location Search provider"
          }
         ],
         "customField2": "",
         "customField3": "",
         "customField4": "",
         "customField5": "",
         "customField6": "",
         "customField7": "",
         "customField8": "",
         "customField9": "",
         "customField10": "",
         "customField11": "",
         "customField12": "",
         "customField13": "",
         "customField14": "",
         "customField15": "",
         "customField16": "",
         "customField17": "",
         "customField18": "",
         "customField19": "",
         "customField20": "",
         "customField21": "",
         "customField22": "",
         "customField23": "",
         "customField24": "",
         "customField25": "",
         "customField26": "",
         "customField27": "",
         "customField28": "",
         "customField29": "",
         "customField30": "",
         "customField31": "",
         "customField32": "",
         "customField33": "",
         "customField34": "",
         "customField35": "",
         "customField36": "",
         "customField37": "",
         "customField38": "",
         "customField39": "",
         "customField40": "",
         "customField41": "",
         "customField42": "",
         "customField43": "",
         "customField44": "",
         "customField45": "",
         "customField46": "",
         "customField47": "",
         "customField48": "",
         "customField49": "",
         "customField50": "",
         "customField51": "",
         "customField52": "",
         "customField53": "",
         "customField54": "",
         "customField55": "",
         "customField56": "",
         "customField57": "",
         "customField58": "",
         "customField59": "",
         "customField60": "",
         "customField61": "",
         "customField62": "",
         "customField63": "",
         "customField64": "",
         "customField65": "",
         "customField66": "",
         "customField67": "",
         "customField68": "",
         "customField69": "",
         "customField70": "",
         "customField71": "",
         "customField72": "",
         "customField73": "",
         "customField74": "",
         "customField75": "",
         "customField76": "",
         "customField77": "",
         "customField78": "",
         "customField79": "",
         "customField80": "",
         "customField81": "",
         "customField82": "",
         "customField83": "",
         "customField84": "",
         "customField85": "",
         "customField86": "",
         "customField87": "",
         "customField88": "",
         "customField89": "",
         "customField90": "",
         "customField91": "",
         "customField92": "",
         "customField93": "",
         "customField94": "",
         "customField95": "",
         "customField96": "",
         "customField97": "",
         "customField98": "",
         "customField99": "",
         "customField100": ""
        }
       }
      };
