module.exports = {
 "totalCount": 6,
 "remarks": [
  {
   "CommonEventId": 205,
   "CustomData": null,
   "AgencyEventId": null,
   "ItemType": 4,
   "TimeStamp": "2023-03-15T13:37:18+00:00",
   "Id": 1970,
   "InfoScope": "",
   "EntryText": "** Created the event at 03/15/23 13:37:18",
   "Term": "EVENTCMDS-FB9C9",
   "IsSystemComment": true,
   "CreatedEmployeeId": 11,
   "CreatedEmployeeName": "Bloggs, Joe",
   "AdornedCommentText": "",
   "AdornedCommentStyle": "",
   "EmployeeAvatar": "",
   "ScopeGroup": "",
   "CommentType": 1,
   "Priority": 0
  },
  {
   "CommonEventId": 205,
   "CustomData": null,
   "AgencyEventId": null,
   "ItemType": 4,
   "TimeStamp": "2023-03-15T13:37:18+00:00",
   "Id": 1971,
   "InfoScope": "",
   "EntryText": "** SS search completed at 03/15/23 13:37:18",
   "Term": "loi-7697758b48-wsqvh",
   "IsSystemComment": true,
   "CreatedEmployeeId": 0,
   "CreatedEmployeeName": ",",
   "AdornedCommentText": "",
   "AdornedCommentStyle": "",
   "EmployeeAvatar": "",
   "ScopeGroup": "",
   "CommentType": 1,
   "Priority": 0
  },
  {
   "CommonEventId": 205,
   "CustomData": null,
   "AgencyEventId": null,
   "ItemType": 4,
   "TimeStamp": "2023-03-15T13:37:19+00:00",
   "Id": 1972,
   "InfoScope": "",
   "EntryText": "** LOI search completed at 03/15/23 13:37:19",
   "Term": "loi-7697758b48-wsqvh",
   "IsSystemComment": true,
   "CreatedEmployeeId": 0,
   "CreatedEmployeeName": ",",
   "AdornedCommentText": "",
   "AdornedCommentStyle": "",
   "EmployeeAvatar": "",
   "ScopeGroup": "",
   "CommentType": 1,
   "Priority": 0
  },
  {
   "CommonEventId": 205,
   "CustomData": null,
   "AgencyEventId": null,
   "ItemType": 4,
   "TimeStamp": "2023-03-15T13:37:19+00:00",
   "Id": 1973,
   "InfoScope": "",
   "EntryText": "AgencyEventCustom11 changed from   to 2023-03-15T01:52:18+00:00\r\n",
   "Term": "EVENTCMDS-FB9C9",
   "IsSystemComment": true,
   "CreatedEmployeeId": 82,
   "CreatedEmployeeName": "System, Monitor Dispatch Times",
   "AdornedCommentText": "",
   "AdornedCommentStyle": "",
   "EmployeeAvatar": "",
   "ScopeGroup": "",
   "CommentType": 1,
   "Priority": 0
  },
  {
   "CommonEventId": 205,
   "CustomData": null,
   "AgencyEventId": null,
   "ItemType": 4,
   "TimeStamp": "2023-03-15T13:37:19+00:00",
   "Id": 1974,
   "InfoScope": "",
   "EntryText": "Target Response Time 15 minutes (13:52:19)",
   "Term": "EVENTCMDS-FB9C9",
   "IsSystemComment": false,
   "CreatedEmployeeId": 82,
   "CreatedEmployeeName": "System, Monitor Dispatch Times",
   "AdornedCommentText": "",
   "AdornedCommentStyle": "",
   "EmployeeAvatar": "",
   "ScopeGroup": "",
   "CommentType": 0,
   "Priority": 0
  },
  {
   "CommonEventId": 205,
   "CustomData": null,
   "AgencyEventId": null,
   "ItemType": 4,
   "TimeStamp": "2023-03-15T13:37:19+00:00",
   "Id": 1975,
   "InfoScope": "",
   "EntryText": "Incident automatically routed to the following functions:\nForensics\n\nTagged with reason: SOCO",
   "Term": "EVENTCMDS-FB9C9",
   "IsSystemComment": false,
   "CreatedEmployeeId": 81,
   "CreatedEmployeeName": "System, Incident Routing",
   "AdornedCommentText": "",
   "AdornedCommentStyle": "",
   "EmployeeAvatar": "",
   "ScopeGroup": "",
   "CommentType": 0,
   "Priority": 0
  }
 ]
}